[package]
name = "libdox"
version = "0.1.0"
edition = "2021"

[dependencies]
dox_derive = { path = "../dox_derive" }
serde = { version = "1.0.210", features = ["serde_derive"] }

[dev-dependencies]
indoc = "2.0.5"
pretty_assertions = "1.4.1"

